/* 「DHCP と DNS・NTP・SNMP」（dhcpword）の過去問。手で直さない。
   scripts/matching.py が out/full/master.jsonl から作る。 */
(function (global) {
  "use strict";
  var BANKS = global.BANKS = global.BANKS || {};
  BANKS.dhcpword = [
  {"qid": "B1-P11-034", "from": ["B1-P11-034"], "book": "B1", "text": "DNSコマンドの対応づけ（ドラッグアンドドロップ）", "kind": "match", "pairs": [{"l": "ホストから IP アドレスへの変換を有効にします", "r": "ip domain lookup"}, {"l": "ホストテーブルにエントリを追加します", "r": "ip host switch_1 192.168.0.1"}, {"l": "アドレスマッピング情報を表示します", "r": "show hosts"}, {"l": "DNS サーバーの IP アドレスを指定します", "r": "ip name-server"}, {"l": "不完全なホスト名にドメイン名を補完します", "r": "ip domain name"}], "targets": ["ip domain lookup", "ip host switch_1 192.168.0.1", "show hosts", "ip name-server", "ip domain name"], "explanation": "ドラッグする項目の一覧は印刷されておらず、答えの対応づけのみ記載"},
  {"qid": "B1-P12-001", "from": ["B1-P12-001"], "book": "B1", "text": "SNMPの対応づけ（ドラッグアンドドロップ）", "kind": "match", "pairs": [{"l": "SNMP によって制御されるネットワーク ノード", "r": "管理対象デバイス"}, {"l": "SNMP 経由で状態を照会できる一意に識別可能なオブジェクトのコレクション", "r": "MIB"}, {"l": "監視アプリケーションを実行し、ネットワーク ノードを制御するシステム", "r": "NMS"}, {"l": "デバイスとネットワーク データをキャプチャして変換する SNMP コンポーネント", "r": "エージェント"}], "targets": ["管理対象デバイス", "MIB", "NMS", "エージェント"], "explanation": "ドラッグする項目の一覧は印刷されておらず、答えの対応づけのみ記載"},
  {"qid": "B1-P12-063", "from": ["B1-P12-063"], "book": "B1", "text": "DNSの対応づけ（ドラッグアンドドロップ）", "kind": "match", "pairs": [{"l": "個々のインターフェースで DNS ルックアップを有効にします", "r": "ip domain lookup source-interface"}, {"l": "デバイスで DNS サーバーを有効にします", "r": "ip dns server"}, {"l": "ルックアップ サービスを提供する DNS サーバーを指定します", "r": "ip name-server"}, {"l": "ドメイン名のシーケンスを指定します", "r": "ip domain list"}, {"l": "修飾されていないホスト名に追加するデフォルトのドメインを指定します", "r": "ip domain name"}, {"l": "IP アドレスをホスト名に静的にマッピングします", "r": "ip host"}], "targets": ["ip domain lookup source-interface", "ip dns server", "ip name-server", "ip domain list", "ip domain name", "ip host"], "explanation": "ドラッグする項目の一覧は印刷されておらず、答えの対応づけのみ記載"},
  {"qid": "B2-0001-02", "from": ["B2-0001-02", "B2-0265-01", "B2-DND-0265-2"], "book": "B2", "text": "SNMP コンポーネントを左側から右側の説明にドラッグ アンド ドロップします。", "kind": "match", "pairs": [{"l": "SNMP 経由で状態を問い合わせることができる、一意に識別可能なオブジェクトのコレクション", "r": "MIB"}, {"l": "SNMPによるネットワークノード制御", "r": "管理対象デバイス"}, {"l": "監視アプリケーションを実行し、ネットワークノードを制御するシステム", "r": "NMS"}, {"l": "デバイスとネットワークのデータをキャプチャして変換するSNMPコンポーネント", "r": "エージェント"}], "targets": ["MIB", "管理対象デバイス", "NMS", "エージェント"], "explanation": "冊の前半 face 0001 の DRAG DROP「SNMP コンポーネント」に対する解答表。パイロットの推定（B2-0001-02）と一致する"},
  {"qid": "B2-0005-01", "from": ["B2-0005-01", "B2-0265-03", "B2-DND-0265-10"], "book": "B2", "text": "標準の DNS ルックアップ操作のステップを左側から右側の順序にドラッグ アンド ドロップします。", "kind": "match", "pairs": [{"l": "エンドポイントはドメイン名の IP アドレスの要求を送信します。", "r": "ステップ1"}, {"l": "DNS はルート DNS サーバーに要求を送信します。", "r": "ステップ2"}, {"l": "DNS はドメイン DNS サーバーに要求を送信します。", "r": "ステップ3"}, {"l": "DNS はドメイン DNS サーバーから応答を受信します。", "r": "ステップ4"}, {"l": "DNS はエンドポイントに応答します。", "r": "ステップ5"}], "targets": ["ステップ1", "ステップ2", "ステップ3", "ステップ4", "ステップ5"], "explanation": "DNS 解決の手順（順序づけ）の解答表"},
  {"qid": "B2-0007-01", "from": ["B2-0007-01", "B2-0266-01", "B2-DND-0266-15"], "book": "B2", "text": "DNS ルックアップ コマンドを左側から右側の関数にドラッグ アンド ドロップします。", "kind": "match", "pairs": [{"l": "個々のインターフェースでDNSルックアップを有効にする", "r": "ip domain lookup source-interface"}, {"l": "デバイス上のDNSサーバーを有効にする", "r": "ip dns server"}, {"l": "検索サービスを提供するDNSサーバーを識別します", "r": "ip name-server"}, {"l": "一連のドメイン名を指定します", "r": "ip domain list"}, {"l": "修飾されていないホスト名に追加するデフォルトのドメインを指定します", "r": "ip domain name"}, {"l": "IPアドレスをホスト名に静的にマッピングする", "r": "ip host"}], "targets": ["ip domain lookup source-interface", "ip dns server", "ip name-server", "ip domain list", "ip domain name", "ip host"], "explanation": ""}
  ];
  if (typeof module !== "undefined" && module.exports) module.exports = BANKS.dhcpword;
})(typeof window !== "undefined" ? window : globalThis);
