/* 「DHCP と DNS・NTP・SNMP」（dhcpword）の過去問。手で直さない。
   scripts/matching.py が out/full/master.jsonl から作る。 */
(function (global) {
  "use strict";
  var BANKS = global.BANKS = global.BANKS || {};
  BANKS.dhcpword = [
  {"qid": "B1-P11-034#1", "from": ["B1-P11-034"], "book": "B1", "text": "この説明は、どれにあてはまりますか。", "exhibit": "DNS サーバーの IP アドレスを指定します", "choices": ["ip domain name", "ip host switch_1 192.168.0.1", "ip domain-lookup", "ip name-server"], "answer": "ip name-server", "explanation": ""},
  {"qid": "B1-P11-034#2", "from": ["B1-P11-034"], "book": "B1", "text": "この説明は、どれにあてはまりますか。", "exhibit": "アドレスマッピング情報を表示します", "choices": ["ip domain name", "ip name-server", "show hosts", "ip host switch_1 192.168.0.1"], "answer": "show hosts", "explanation": ""},
  {"qid": "B1-P11-034#3", "from": ["B1-P11-034"], "book": "B1", "text": "この説明は、どれにあてはまりますか。", "exhibit": "ホストから IP アドレスへの変換を有効にします", "choices": ["show hosts", "ip domain name", "ip domain-lookup", "ip host switch_1 192.168.0.1"], "answer": "ip domain-lookup", "explanation": ""},
  {"qid": "B1-P11-034#4", "from": ["B1-P11-034"], "book": "B1", "text": "この説明は、どれにあてはまりますか。", "exhibit": "ホストテーブルにエントリを追加します", "choices": ["show hosts", "ip name-server", "ip domain-lookup", "ip host switch_1 192.168.0.1"], "answer": "ip host switch_1 192.168.0.1", "explanation": ""},
  {"qid": "B1-P11-034#5", "from": ["B1-P11-034"], "book": "B1", "text": "この説明は、どれにあてはまりますか。", "exhibit": "不完全なホスト名にドメイン名を補完します", "choices": ["ip domain name", "ip domain-lookup", "ip host switch_1 192.168.0.1", "show hosts"], "answer": "ip domain name", "explanation": ""},
  {"qid": "B1-P12-001#1", "from": ["B1-P12-001"], "book": "B1", "text": "この説明は、どれにあてはまりますか。", "exhibit": "SNMP によって制御されるネットワーク ノード", "choices": ["エージェント", "管理対象デバイス", "NMS", "MIB"], "answer": "管理対象デバイス", "explanation": ""},
  {"qid": "B1-P12-001#2", "from": ["B1-P12-001"], "book": "B1", "text": "この説明は、どれにあてはまりますか。", "exhibit": "SNMP 経由で状態を照会できる一意に識別可能なオブジェクトのコレクション", "choices": ["MIB", "エージェント", "NMS", "管理対象デバイス"], "answer": "MIB", "explanation": ""},
  {"qid": "B1-P12-001#3", "from": ["B1-P12-001"], "book": "B1", "text": "この説明は、どれにあてはまりますか。", "exhibit": "デバイスとネットワーク データをキャプチャして変換する SNMP コンポーネント", "choices": ["NMS", "MIB", "エージェント", "管理対象デバイス"], "answer": "エージェント", "explanation": ""},
  {"qid": "B1-P12-001#4", "from": ["B1-P12-001", "B2-0001-02", "B2-0265-01", "B2-DND-0265-2"], "book": "B1", "text": "この説明は、どれにあてはまりますか。", "exhibit": "監視アプリケーションを実行し、ネットワークノードを制御するシステム", "choices": ["エージェント", "管理対象デバイス", "MIB", "NMS"], "answer": "NMS", "explanation": "同じ対は B2-0001-02・B2-0265-01・B2-DND-0265-2 にも出ます。"},
  {"qid": "B1-P12-063#1", "from": ["B1-P12-063"], "book": "B1", "text": "この説明は、どれにあてはまりますか。", "exhibit": "IP アドレスをホスト名に静的にマッピングします", "choices": ["ip name-server", "ip domain name", "ip host", "ip domain lookup source-interface"], "answer": "ip host", "explanation": ""},
  {"qid": "B1-P12-063#2", "from": ["B1-P12-063"], "book": "B1", "text": "この説明は、どれにあてはまりますか。", "exhibit": "デバイスで DNS サーバーを有効にします", "choices": ["ip dns server", "ip host", "ip domain lookup source-interface", "ip domain name"], "answer": "ip dns server", "explanation": ""},
  {"qid": "B1-P12-063#3", "from": ["B1-P12-063"], "book": "B1", "text": "この説明は、どれにあてはまりますか。", "exhibit": "ドメイン名のシーケンスを指定します", "choices": ["ip dns server", "ip domain list", "ip name-server", "ip domain name"], "answer": "ip domain list", "explanation": ""},
  {"qid": "B1-P12-063#4", "from": ["B1-P12-063"], "book": "B1", "text": "この説明は、どれにあてはまりますか。", "exhibit": "ルックアップ サービスを提供する DNS サーバーを指定します", "choices": ["ip domain list", "ip name-server", "ip domain lookup source-interface", "ip domain name"], "answer": "ip name-server", "explanation": ""},
  {"qid": "B1-P12-063#5", "from": ["B1-P12-063", "B2-0007-01"], "book": "B1", "text": "この説明は、どれにあてはまりますか。", "exhibit": "修飾されていないホスト名に追加するデフォルトのドメインを指定します", "choices": ["ip host", "ip domain lookup source-interface", "ip domain list", "ip domain name"], "answer": "ip domain name", "explanation": "同じ対は B2-0007-01 にも出ます。"},
  {"qid": "B1-P12-063#6", "from": ["B1-P12-063"], "book": "B1", "text": "この説明は、どれにあてはまりますか。", "exhibit": "個々のインターフェースで DNS ルックアップを有効にします", "choices": ["ip domain list", "ip domain name", "ip host", "ip domain lookup source-interface"], "answer": "ip domain lookup source-interface", "explanation": ""},
  {"qid": "B2-0001-02#1", "from": ["B2-0001-02", "B2-0265-01", "B2-DND-0265-2"], "book": "B2", "text": "この説明は、どれにあてはまりますか。", "exhibit": "SNMPによるネットワークノード制御", "choices": ["管理対象デバイス", "NMS", "エージェント", "MIB"], "answer": "管理対象デバイス", "explanation": "同じ対は B2-0265-01・B2-DND-0265-2 にも出ます。"},
  {"qid": "B2-0001-02#2", "from": ["B2-0001-02", "B2-0265-01", "B2-DND-0265-2"], "book": "B2", "text": "この説明は、どれにあてはまりますか。", "exhibit": "SNMP 経由で状態を問い合わせることができる、一意に識別可能なオブジェクトのコレクション", "choices": ["NMS", "管理対象デバイス", "エージェント", "MIB"], "answer": "MIB", "explanation": "同じ対は B2-0265-01・B2-DND-0265-2 にも出ます。"},
  {"qid": "B2-0001-02#3", "from": ["B2-0001-02", "B2-0265-01", "B2-DND-0265-2"], "book": "B2", "text": "この説明は、どれにあてはまりますか。", "exhibit": "デバイスとネットワークのデータをキャプチャして変換するSNMPコンポーネント", "choices": ["管理対象デバイス", "MIB", "NMS", "エージェント"], "answer": "エージェント", "explanation": "同じ対は B2-0265-01・B2-DND-0265-2 にも出ます。"},
  {"qid": "B2-0005-01#1", "from": ["B2-0005-01", "B2-0265-03", "B2-DND-0265-10"], "book": "B2", "text": "この説明は、どれにあてはまりますか。", "exhibit": "DNS はエンドポイントに応答します。", "choices": ["ステップ2", "ステップ1", "ステップ4", "ステップ5"], "answer": "ステップ5", "explanation": "同じ対は B2-0265-03・B2-DND-0265-10 にも出ます。"},
  {"qid": "B2-0005-01#2", "from": ["B2-0005-01", "B2-0265-03", "B2-DND-0265-10"], "book": "B2", "text": "この説明は、どれにあてはまりますか。", "exhibit": "DNS はドメイン DNS サーバーから応答を受信します。", "choices": ["ステップ4", "ステップ2", "ステップ5", "ステップ1"], "answer": "ステップ4", "explanation": "同じ対は B2-0265-03・B2-DND-0265-10 にも出ます。"},
  {"qid": "B2-0005-01#3", "from": ["B2-0005-01", "B2-0265-03", "B2-DND-0265-10"], "book": "B2", "text": "この説明は、どれにあてはまりますか。", "exhibit": "DNS はドメイン DNS サーバーに要求を送信します。", "choices": ["ステップ1", "ステップ3", "ステップ5", "ステップ2"], "answer": "ステップ3", "explanation": "同じ対は B2-0265-03・B2-DND-0265-10 にも出ます。"},
  {"qid": "B2-0005-01#4", "from": ["B2-0005-01", "B2-0265-03", "B2-DND-0265-10"], "book": "B2", "text": "この説明は、どれにあてはまりますか。", "exhibit": "DNS はルート DNS サーバーに要求を送信します。", "choices": ["ステップ4", "ステップ1", "ステップ2", "ステップ5"], "answer": "ステップ2", "explanation": "同じ対は B2-0265-03・B2-DND-0265-10 にも出ます。"},
  {"qid": "B2-0005-01#5", "from": ["B2-0005-01", "B2-0265-03", "B2-DND-0265-10"], "book": "B2", "text": "この説明は、どれにあてはまりますか。", "exhibit": "エンドポイントはドメイン名の IP アドレスの要求を送信します。", "choices": ["ステップ1", "ステップ2", "ステップ3", "ステップ5"], "answer": "ステップ1", "explanation": "同じ対は B2-0265-03・B2-DND-0265-10 にも出ます。"},
  {"qid": "B2-0007-01#1", "from": ["B2-0007-01"], "book": "B2", "text": "この説明は、どれにあてはまりますか。", "exhibit": "IPアドレスをホスト名に静的にマッピングする", "choices": ["ip name-server", "ip host", "ip dns server", "ip domain list"], "answer": "ip host", "explanation": ""},
  {"qid": "B2-0007-01#2", "from": ["B2-0007-01"], "book": "B2", "text": "この説明は、どれにあてはまりますか。", "exhibit": "デバイス上のDNSサーバーを有効にする", "choices": ["ip name-server", "ip host", "ip domain list", "ip dns server"], "answer": "ip dns server", "explanation": ""},
  {"qid": "B2-0007-01#3", "from": ["B2-0007-01"], "book": "B2", "text": "この説明は、どれにあてはまりますか。", "exhibit": "一連のドメイン名を指定します", "choices": ["ip domain name", "ip dns server", "ip domain lookup source-interface", "ip domain list"], "answer": "ip domain list", "explanation": ""},
  {"qid": "B2-0007-01#4", "from": ["B2-0007-01"], "book": "B2", "text": "この説明は、どれにあてはまりますか。", "exhibit": "個々のインターフェースでDNSルックアップを有効にする", "choices": ["ip domain name", "ip dns server", "ip name-server", "ip domain lookup source-interface"], "answer": "ip domain lookup source-interface", "explanation": ""},
  {"qid": "B2-0007-01#5", "from": ["B2-0007-01"], "book": "B2", "text": "この説明は、どれにあてはまりますか。", "exhibit": "検索サービスを提供するDNSサーバーを識別します", "choices": ["ip domain lookup source-interface", "ip dns server", "ip name-server", "ip domain name"], "answer": "ip name-server", "explanation": ""}
  ];
  if (typeof module !== "undefined" && module.exports) module.exports = BANKS.dhcpword;
})(typeof window !== "undefined" ? window : globalThis);
