/* 「json」の過去問。手で直さない。scripts/json_block.py --write が作る。
 *
 * exhibit は2つに分かれている。
 *   src   … 本の提示物そのまま。**画面に出るのはこれだけ。**
 *   asked … 本の問題文から起こした「何が聞かれているか」。判定のもとになる。
 *           同じ JSON でも、聞かれているものが違えば答えが違うため。
 *
 * asked の形は showread/types/json.js の頭に書いてある。
 */
(function (global) {
  "use strict";
  var BANKS = global.BANKS = global.BANKS || {};
  BANKS.json = [
  {"qid": "B1-P11-029", "book": "B1", "text": "JSON オブジェクトの数はいくつですか。", "exhibit": {"src": "{\n \"SW1\": [\"Ten-GigabitEthernet0/0\", \"Ten-GigabitEthernet0/1\"],\n \"SW2\": [\"Ten-GigabitEthernet0/0\", \"Ten-GigabitEthernet0/1\"],\n \"SW3\": [\"Ten-GigabitEthernet0/0\", \"Ten-GigabitEthernet0/1\"],\n \"SW4\": [\"Ten-GigabitEthernet0/0\", \"Ten-GigabitEthernet0/1\"]\n}", "asked": {"mode": "count", "what": "オブジェクト"}}, "choices": ["1", "2", "3", "4"], "answer": "1", "explanation": "オブジェクトは{}のこと"},
  {"qid": "B1-P11-066", "book": "B1", "text": "JSON データにはいくつの配列がありますか。", "exhibit": {"src": "{\n  \"Test_Questions\" : [\n        \"Automation\",\n        \"Configuration\",\n  ],\n  \"Test_Exam_Level\" : [\n        \"CCNA\",\n        \"CCNP\",\n  ],\n  \"Test_Response\" : [\n        \"Correct\",\n        \"Incorrect\",\n  ]\n}", "asked": {"mode": "count", "what": "配列"}}, "choices": ["1つ", "3つ", "6つ", "9つ"], "answer": "3つ", "explanation": "改行されていて分かりにくいですが、配列は[\"A\",\"B\"]の形式です。"},
  {"qid": "B1-P12-017", "book": "B1", "text": "JSON スキーマの 2 行目の「switch」という単語は何を表していますか。", "exhibit": {"src": "[\n  {\"switch\"： \"3750\", \"port\"： \"e2\"},\n  {\"router\"： \"2951\", \"port\"： \"e20\"},\n  {\"switch\"： \"3750\", \"port\"： \"e23\"}\n]", "asked": {"mode": "word", "word": "switch"}}, "choices": ["object（オブジェクト）", "key（キー）", "value（値）", "array（配列）"], "answer": "key（キー）", "explanation": "\"key\":値、オブジェクト{}、配列[]"},
  {"qid": "B1-P12-050", "book": "B1", "text": "オブジェクト、キー、JSON リスト値はいくつありますか。", "exhibit": {"src": "{\n  \"Test_Questions\": [\"Automation\", \"Configuration\"],\n  \"Test__Exam_Level\": [\"CCNA\", \"CCNP\"],\n  \"Test_Response\": [\"Correct\", \"Incorrect\"]\n}", "asked": {"mode": "countset", "whats": ["オブジェクト", "キー", "JSON リスト値"]}}, "choices": ["3 つのオブジェクト、3 つのキー、2 つの JSON リスト値", "1 つのオブジェクト、3 つのキー、2 つの JSON リスト値", "3 つのオブジェクト、2 つのキー、3 つの JSON リスト値", "1 つのオブジェクト、3 つのキー、3 つの JSON リスト値"], "answer": "1 つのオブジェクト、3 つのキー、3 つの JSON リスト値", "explanation": "\"key\":\"値\"、オブジェクト{}、配列[] リスト値の数＝配列の数"},
  {"qid": "B1-P13-037", "book": "B1", "text": "この JSON スキーマ内の「port」という単語は何を表していますか。", "exhibit": {"src": "1  [\n2  {\"IDS\": \"IPS_pittsburgh\", \"port\":\"te8/30\"},\n3  {\"router\": \"R20\", \"port\":\"ge9/23\"},\n4  {\"firewall\": \"FW42\", \"port\":\"fe3/24\"},\n5  ]", "asked": {"mode": "word", "word": "port"}}, "choices": ["バリュー", "配列", "キー", "オブジェクト"], "answer": "キー", "explanation": "[]は配列、{}はオブジェクト、{\"key\" : \"value\"}"},
  {"qid": "B1-P13-040", "book": "B1", "text": "この JSON スキーマ内の単語「ge3/36」は何を表していますか。", "exhibit": {"src": "1 [\n2 {\"VPN concentrator\": \"VPN36\", \"interface\":\"ge3/36\"},\n3 {\"load balancer\": \"LB33\", \"interface\":\"te7/10\"},\n4 {\"switch\": \"SW31\", \"interface\":\"fe2/25\"},\n5 ]", "asked": {"mode": "word", "word": "ge3/36"}}, "choices": ["値", "配列", "キー", "オブジェクト"], "answer": "値", "explanation": "\"key\":\"値\"、オブジェクト{}、配列[]"},
  {"qid": "B1-P13-073", "book": "B1", "text": "1 行目から 5 行目で終わる部分は何が表されますか。", "exhibit": {"src": "1 [\n2  {\"switch\": \"3750\", \"port\": \"e2\"},\n3  {\"router\": \"2951\", \"port\": \"e20\"},\n4  {\"switch\": \"3750\", \"port\": \"e23\"}\n5 ]", "asked": {"mode": "line", "lineno": 1, "to": 5, "lang": "en"}}, "choices": ["object", "key", "value", "array"], "answer": "array", "explanation": "\"key\":\"値\"、オブジェクト{}、配列[]"},
  {"qid": "B1-P14-003", "book": "B1", "text": "この JSON スキーマ内の「R20」という単語は何を表していますか。", "exhibit": {"src": "[\n{\"firewall\": \"FW12\", \"port\":\"e0/23\"},\n{\"router\": \"R20\", \"port\":\"te5/5\"},\n{\"switch\": \"SW25\", \"port\":\"ge1/36\"},\n5   ]", "asked": {"mode": "word", "word": "R20", "lang": "en"}}, "choices": ["value", "array", "key", "object"], "answer": "value", "explanation": "JSONは「\"キー\" : \"バリュー\"」という構文です。例えばfirewallはキー、FW12はバリューです。"},
  {"qid": "B1-P14-051", "book": "B1", "text": "表示されている JSON データ型はどれですか。", "exhibit": {"src": "{\n\"interface\":[\"ethernet0/3\", \"ethernet0/4\", \"ethernet0/5\"]\n}", "asked": {"mode": "whole"}}, "choices": ["文字列", "配列", "オブジェクト", "bool値"], "answer": "オブジェクト", "explanation": "{}で囲われているためオブジェクトが正しい。ただし、[,,]は配列、\"\"は文字列であり、問題が不親切に思える。bool値とはtrue/falseのこと。"},
  {"qid": "B1-P15-078", "book": "B1", "text": "このJSONスキーマ内の「switch」という単語は何を表していますか？", "exhibit": {"src": "1  [\n2  {\"IDS\": \"IPS22\", \"port\":\"te3/46\"},\n3  {\"load balancer\": \"LB12\", \"port\":\"te6/38\"},\n4  {\"switch\": \"SW18\", \"port\":\"ge2/41\"},\n5  ]", "asked": {"mode": "word", "word": "switch"}}, "choices": ["配列", "値", "キー", "オブジェクト"], "answer": "キー", "explanation": "\"key\":\"値\"、オブジェクト{}、配列[]"},
  {"qid": "B1-P16-029", "book": "B1", "text": "この JSON スキーマ内の 2 行目には何が表されていますか?", "exhibit": {"src": "1  [\n2  {\"switch\": \"SW_admin\", \"interface\":\"ge7/41\"},\n3  {\"VPN concentrator\": \"VPN_finance\", \"interface\":\"fe9/5\"},\n4  {\"IDS\": \"IPS_admin\", \"interface\":\"te2/10\"},\n5  ]", "asked": {"mode": "line", "lineno": 2, "lang": "en"}}, "choices": ["array", "value", "key", "object"], "answer": "object", "explanation": "{}はオブジェクト。{} の中にキー(左)と値(右)をコロンで区切って記述します。"},
  {"qid": "B1-P16-072", "book": "B1", "text": "この JSON スキーマ内の 3 行目には何が表されていますか。", "exhibit": {"src": "1  [\n2  {\"switch\": \"SW_dallas\", \"port\":\"ge16\"},\n3  {\"load balancer\": \"LB_munich\", \"port\":\"te8/26\"},\n4  {\"VPN concentrator\": \"VPN_toronto\", \"port\":\"te8/15\"},\n5  ]", "asked": {"mode": "line", "lineno": 3}}, "choices": ["配列", "値", "キー", "オブジェクト"], "answer": "オブジェクト", "explanation": "キー\"\"、オブジェクト{}、配列[]"},
  {"qid": "B2-0026-03", "book": "B2", "text": "展示品をご参照ください。「警告」という言葉はどの構造に直接存在するのでしょうか?", "exhibit": {"src": "{\n    \"myCar\": {\n            \"name\": \"thunder\",\n            \"wheels\": [\"good\", \"good\", \"pressurelow\", \"warning\"],\n            \"gasLight\": false\n            },\n    \"oldCar\": {\n            \"name\": \"sleepy\",\n            \"wheels\": [\"pressurelow\", \"pressurelow\", \"pressurelow\", \"pressurelow\"],\n            \"color\": \"rust\",\n            \"gasLight\": true\n            },\n    \"newCar\": {\n            \"name\": \"lightning\",\n            \"wheels\": [\"pressurelow\", \"good\", \"pressurelow\", \"good\"],\n            \"color\": \"blue\",\n            \"gasLight\": true\n            }\n}", "asked": {"mode": "word", "word": "warning"}}, "choices": ["配列", "オブジェクト", "ブール値", "文字列"], "answer": "配列", "explanation": ""},
  {"qid": "B2-0031-03", "book": "B2", "text": "展示品をご参照ください。 JSON データ内で apple は何を表しますか?", "exhibit": {"src": "{\"apple\": [\"red\", 1], \"ripe\": true}", "asked": {"mode": "type", "word": "apple"}}, "choices": ["配列", "オブジェクト", "番号", "文字列"], "answer": "文字列", "explanation": ""},
  {"qid": "B2-0034-01", "book": "B2", "text": "展示品をご参照ください。 JSON データには配列がいくつ存在しますか?", "exhibit": {"src": "{\n        \"Test_Questions\" : [\n                        \"Automation\",\n                        \"Configuration\",\n        ],\n        \"Test_Exam_Level\" : [\n                        \"CCNA\",\n                        \"CCNP\",\n        ],\n        \"Test_Response\" : [\n                        \"Correct\",\n                        \"Incorrect\",\n        ]\n}", "asked": {"mode": "count", "what": "配列"}}, "choices": ["1", "3", "6", "9"], "answer": "3", "explanation": ""},
  {"qid": "B2-0069-01", "book": "B2", "text": "この JSON スキーマ内の「LB20」という単語は何を表しますか?", "exhibit": {"src": "1 [\n2 {\"load balancer\": \"LB20\", \"interface\": \"te4/3\"},\n3 {\"firewall\": \"FW49\", \"interface\": \"ge4/14\"},\n4 {\"IDS\": \"IPS_frankfurt\", \"interface\": \"e9/7\"}\n5 ]", "asked": {"mode": "word", "word": "LB20"}}, "choices": ["値", "配列", "オブジェクト", "キー"], "answer": "値", "explanation": ""},
  {"qid": "B2-0070-01", "book": "B2", "text": "この JSON スキーマ内の 1 行目から 5 行目で終わるものは何で表されますか?", "exhibit": {"src": "1 [\n2 {\"firewall\": \"FW24\", \"interface\": \"fe1/34\"},\n3 {\"switch\": \"SWseattle\", \"interface\": \"ge8/21\"},\n4 {\"IDS\": \"IPSsydney\", \"interface\": \"te2/43\"}\n5 ]", "asked": {"mode": "line", "lineno": 1, "to": 5}}, "choices": ["キー", "オブジェクト", "配列", "値"], "answer": "配列", "explanation": ""},
  {"qid": "B2-0070-02", "book": "B2", "text": "この JSON スキーマ内の「IDS」という単語は何を表しますか?", "exhibit": {"src": "1 [\n2 {\"firewall\": \"FW_portland\", \"port\": \"e2/5\"},\n3 {\"IDS\": \"IPS31\", \"port\": \"ge0/28\"},\n4 {\"load balancer\": \"LB48\", \"port\": \"fe0/43\"}\n5 ]", "asked": {"mode": "word", "word": "IDS"}}, "choices": ["オブジェクト", "値", "配列", "キー"], "answer": "キー", "explanation": ""},
  {"qid": "B2-0071-01", "book": "B2", "text": "この JSON スキーマの 4 行目では何が表されていますか?", "exhibit": {"src": "1 [\n2 {\"switch\": \"SWbarcelona\", \"interface\": \"ge1/40\"},\n3 {\"firewall\": \"FWamsterdam\", \"interface\": \"fe21\"},\n4 {\"router\": \"R_frankfurt\", \"interface\": \"te8/30\"}\n5 ]", "asked": {"mode": "line", "lineno": 4}}, "choices": ["オブジェクト", "配列", "キー", "値"], "answer": "オブジェクト", "explanation": ""},
  {"qid": "B2-0071-02", "book": "B2", "text": "この JSON スキーマ内の「ポート」という単語は何を表しますか?", "exhibit": {"src": "1 [\n2 {\"router\": \"R_pittsburgh\", \"port\": \"te6/21\"},\n3 {\"VPN concentrator\": \"VPN47\", \"port\": \"e6/37\"},\n4 {\"firewall\": \"FW28\", \"port\": \"ge7/42\"}\n5 ]", "asked": {"mode": "word", "word": "port"}}, "choices": ["キー", "値", "配列", "オブジェクト"], "answer": "キー", "explanation": ""},
  {"qid": "B2-0078-02", "book": "B2", "text": "この JSON スキーマ内の「VPN11」という単語は何を表しますか?", "exhibit": {"src": "1  [\n2  {\"VPN concentrator\": \"VPN11\", \"port\":\"fe7/12\"},\n3  {\"router\": \"Radmin\", \"port\":\"e5/1\"},\n4  {\"switch\": \"SWbangkok\", \"port\":\"ge6/6\"}\n5  ]", "asked": {"mode": "word", "word": "VPN11"}}, "choices": ["キー", "配列", "オブジェクト", "値"], "answer": "値", "explanation": ""},
  {"qid": "B2-0079-03", "book": "B2", "text": "この JSON スキーマ内の「R29」という単語は何を表しますか?", "exhibit": {"src": "1  [\n2  {\"firewall\": \"FW15\", \"interface\":\"e8/33\"},\n3  {\"switch\": \"SW_chicago\", \"interface\":\"ge5/26\"},\n4  {\"router\": \"R29\", \"interface\":\"fe4/25\"}\n5  ]", "asked": {"mode": "word", "word": "R29"}}, "choices": ["配列", "キー", "オブジェクト", "値"], "answer": "値", "explanation": ""},
  {"qid": "B2-0079-04", "book": "B2", "text": "この JSON スキーマ内の行 2 には何が表されますか?", "exhibit": {"src": "1  [\n2  {\"switch\": \"SW16\", \"interface\":\"fe3/43\"},\n3  {\"load balancer\": \"LBmiami\", \"interface\":\"e0/1\"},\n4  {\"firewall\": \"FWboston\", \"interface\":\"ge6/12\"}\n5  ]", "asked": {"mode": "line", "lineno": 2}}, "choices": ["オブジェクト", "値", "キー", "配列"], "answer": "オブジェクト", "explanation": ""},
  {"qid": "B2-0096-02", "book": "B2", "text": "この JSON スキーマ内の「fe5/42」という単語は何を表しますか?", "exhibit": {"src": "1  [\n2  {\"load balancer\": \"LB_milwaukee\", \"port\":\"fe5/42\"},\n3  {\"VPN concentrator\": \"VPNadmin\", \"port\":\"e1/39\"},\n4  {\"firewall\": \"FW_chicago\", \"port\":\"fe3/42\"},\n5  ]", "asked": {"mode": "word", "word": "fe5/42"}}, "choices": ["配列", "オブジェクト", "値", "キー"], "answer": "値", "explanation": ""},
  {"qid": "B2-0100-01", "book": "B2", "text": "この JSON スキーマ内の「ポート」という単語は何を表しますか?", "exhibit": {"src": "1  [\n2  {\"IDS\": \"IPS_pittsburgh\", \"port\":\"te8/30\"},\n3  {\"router\": \"R20\", \"port\":\"ge9/23\"},\n4  {\"firewall\": \"FW42\", \"port\":\"fe3/24\"},\n5  ]", "asked": {"mode": "word", "word": "port"}}, "choices": ["値", "配列", "キー", "オブジェクト"], "answer": "キー", "explanation": ""},
  {"qid": "B2-0116-03", "book": "B2", "text": "この JSON スキーマ内の行 2 には何が表されますか?", "exhibit": {"src": "1  [\n2  {\"load balancer\": \"LB48\", \"port\":\"e0/27\"},\n3  {\"firewall\": \"FW49\", \"port\":\"ge2/37\"},\n4  {\"router\": \"R_paris\", \"port\":\"te6/6\"},\n5  ]", "asked": {"mode": "line", "lineno": 2}}, "choices": ["オブジェクト", "値", "キー", "配列"], "answer": "オブジェクト", "explanation": ""},
  {"qid": "B2-0117-01", "book": "B2", "text": "この JSON スキーマ内の「ge3/36」という単語は何を表しますか?", "exhibit": {"src": "1  [\n2  {\"VPN concentrator\": \"VPN36\", \"interface\":\"ge3/36\"},\n3  {\"load balancer\": \"LB33\", \"interface\":\"te7/10\"},\n4  {\"switch\": \"SW31\", \"interface\":\"fe2/25\"},\n5  ]", "asked": {"mode": "word", "word": "ge3/36"}}, "choices": ["値", "配列", "オブジェクト", "キー"], "answer": "値", "explanation": ""},
  {"qid": "B2-0120-01", "book": "B2", "text": "この JSON スキーマ内の「ファイアウォール」という単語は何を表しますか?", "exhibit": {"src": "1  [\n2  {\"router\": \"R_pittsburgh\", \"port\":\"e0/36\"},\n3  {\"firewall\": \"FW37\", \"port\":\"te23\"},\n4  {\"switch\": \"SW_toronto\", \"port\":\"ge5/28\"},\n5  ]", "asked": {"mode": "word", "word": "firewall"}}, "choices": ["値", "キー", "オブジェクト", "配列"], "answer": "キー", "explanation": ""},
  {"qid": "B2-0162-01", "book": "B2", "text": "この JSON スキーマ内の「R20」という単語は何を表しますか?", "exhibit": {"src": "1 [\n2 {\"firewall\": \"FW12\", \"port\": \"e0/23\"},\n3 {\"router\": \"R20\", \"port\": \"te5/5\"},\n4 {\"switch\": \"SW25\", \"port\": \"ge1/36\"}\n5 ]", "asked": {"mode": "word", "word": "R20"}}, "choices": ["値", "配列", "オブジェクト", "キー"], "answer": "値", "explanation": ""},
  {"qid": "B2-0169-01", "book": "B2", "text": "この JSON スキーマの 3 行目では何が表されていますか?", "exhibit": {"src": "1 [\n2 {\"switch\": \"SW_dallas\", \"port\": \"ge16\"},\n3 {\"load balancer\": \"LB_munich\", \"port\": \"te0/26\"},\n4 {\"VPN concentrator\": \"VPN_toronto\", \"port\": \"ge8/15\"}\n5 ]", "asked": {"mode": "line", "lineno": 3}}, "choices": ["オブジェクト", "キー", "値", "配列"], "answer": "オブジェクト", "explanation": ""},
  {"qid": "B2-0193-01", "book": "B2", "text": "この JSON スキーマ内の「スイッチ」という単語は何を表しますか?", "exhibit": {"src": "1 [\n2   {\"IDS\": \"IPS22\", \"port\": \"te3/46\"},\n3   {\"load balancer\": \"LB12\", \"port\": \"te6/38\"},\n4   {\"switch\": \"SW18\", \"port\": \"ge2/41\"},\n5 ]", "asked": {"mode": "word", "word": "switch"}}, "choices": ["キー", "オブジェクト", "配列", "値"], "answer": "キー", "explanation": ""},
  {"qid": "B2-0196-02", "book": "B2", "text": "この JSON スキーマ内の「LB13」という単語は何を表しますか?", "exhibit": {"src": "1 [\n2   {\"load balancer\": \"LB13\", \"port\": \"fe9/2\"},\n3   {\"firewall\": \"FW20\", \"port\": \"e2/28\"},\n4   {\"router\": \"R41\", \"port\": \"te7/27\"},\n5 ]", "asked": {"mode": "word", "word": "LB13"}}, "choices": ["配列", "値", "オブジェクト", "キー"], "answer": "値", "explanation": ""},
  {"qid": "B2-0197-01", "book": "B2", "text": "展示品をご参照ください。表示される JSON データのタイプはどれですか?", "exhibit": {"src": "{\n\"Interfaces\":[\"ethernet0/3\", \"ethernet0/4\", \"ethernet0/5\"]\n}", "asked": {"mode": "whole"}}, "choices": ["ブール値", "文字列", "オブジェクト", "シーケンス"], "answer": "オブジェクト", "explanation": ""},
  {"qid": "B2-0242-01", "book": "B2", "text": "展示品をご参照ください。どのタイプの JSON データが表されますか?", "exhibit": {"src": "[\"red\", \"one\"]", "asked": {"mode": "whole"}}, "choices": ["番号", "配列", "オブジェクト", "文字列"], "answer": "配列", "explanation": ""},
  {"qid": "B3-M1-106", "book": "B3", "text": "上記を参照してください。どのタイプの JSON データが表されますか。", "exhibit": {"src": "[\"red\", \"one\"]", "asked": {"mode": "whole"}}, "choices": ["配列", "数字", "文字列", "オブジェクト"], "answer": "配列", "explanation": "[\"red\", \"one\"] は、配列です。JSONの配列は角括弧 [] で囲まれ、その中に複数の値がカンマで区切られて格納されています。この場合、配列には \"red\" と \"one\" という2つの文字列が含まれています。"},
  {"qid": "B3-M2-025", "book": "B3", "text": "この JSON スキーマ内の「fe5/42」という単語は何を表しますか。", "exhibit": {"src": "1  [\n2  {\"load balancer\": \"LB_milwaukee\", \"port\":\"fe5/42\"},\n3  {\"VPN concentrator\": \"VPNadmin\", \"port\":\"e1/39\"},\n4  {\"firewall\": \"FW_chicago\", \"port\":\"fe3/42\"},\n5  ]", "asked": {"mode": "word", "word": "fe5/42"}}, "choices": ["配列", "オブジェクト", "キー", "値"], "answer": "値", "explanation": "この配列では、特に キー:値のペアについて尋ねています。"},
  {"qid": "B3-M2-066", "book": "B3", "text": "この JSON スキーマ内の「port」という単語は何を表しますか。", "exhibit": {"src": "1  [\n2  {\"load balancer\": \"LB_milwaukee\", \"port\":\"fe5/42\"},\n3  {\"VPN concentrator\": \"VPNadmin\", \"port\":\"e1/39\"},\n4  {\"firewall\": \"FW_chicago\", \"port\":\"fe3/42\"},\n5  ]", "asked": {"mode": "word", "word": "port"}}, "choices": ["配列", "オブジェクト", "キー", "値"], "answer": "キー", "explanation": "この配列では、特に キー:値のペアについて尋ねています。"},
  {"qid": "B3-M3-038", "book": "B3", "text": "上記を参照してください。JSON データには配列がいくつ存在しますか。", "exhibit": {"src": "{\n    \"Test_Questions\": [\n        \"Automation\",\n        \"Configuration\"\n    ],\n    \"Test_Exam_Level\": [\n        \"CCNA\",\n        \"CCNP\"\n    ],\n    \"Test_Response\": [\n        \"Correct\",\n        \"Incorrect\"\n    ]\n}", "asked": {"mode": "count", "what": "配列"}}, "choices": ["1", "3", "6", "9"], "answer": "3", "explanation": "上記のJSONデータには3つの配列が存在します。 \"Test_Questions\": [\"Automation\", \"Configuration\"] \"Test_Exam_Level\": [\"CCNA\", \"CCNP\"] \"Test_Response\": [\"Correct\", \"Incorrect\"] 各配列は角かっこ \"[\" と \"]\" の間に要素を含んでいます。したがって、JSONデータには3つの配列があります。"}
  ];
  if (typeof module !== "undefined" && module.exports) module.exports = BANKS.json;
})(typeof window !== "undefined" ? window : globalThis);
