/* 「ログの読み取り」の過去問。手で直さない。
   もとは目標3.4 に分類されていたが、中身は「出力を読んで当てる」。 */
(function (global) {
  "use strict";
  var BANKS = global.BANKS = global.BANKS || {};
  BANKS.log = [
    {"qid": "B1-P16-005", "book": "B1", "text": "このスイッチでは何が起こっているのでしょうか?", "exhibit": "AMDP2_FE-5-COLL: AMDP2/FE 0/0/ [DEC] , Excessive collisions, TDR=[DEC] , TRC=[DEC]\n%DEC21140-5-COLL: [chars] excessive collisions\n%ILACC-5-COLL: Unit [DEC], excessive collisions. TDR=[DEC]\n%LANCE—5-COLL: Unit [DEC], excessive collisions. TDR=[DEC]\n%PQUICC-5-COLL: Unit [DEC], excessive collisions. Retry limit [DEC] exceeded\n%PQUICC_ETHER-5-COLL: Unit [DEC], excessive collisions. Retry limit [DEC] exceeded", "choices": ["64バイト未満のフレームを大量に受信しています。", "16回の送信試行に失敗するとフレームがドロップされます。", "内部送信バッファが過負荷になっています。", "1518バイトを超えるフレームを過剰に受信しています。"], "answer": "16回の送信試行に失敗するとフレームがドロップされます。", "explanation": "フレーム送信時にコリジョンが発生した場合、16回連続で送信に失敗すると「excessive collisions」となり、フレームが破棄されます。"},
    {"qid": "B2-0054-01", "book": "B2", "text": "展示品をご参照ください。このスイッチで何が起こっているのでしょうか?", "exhibit": "%AMDP2_FE-5-COLL: AMDP2/FE 0/0/[DEC], Excessive collisions, TDR=[DEC], TRC=[DEC]\n%DEC21140-5-COLL: [chars] excessive collisions\n%ILACC-5-COLL: Unit [DEC], excessive collisions. TDR=[DEC]\n%LANCE-5-COLL: Unit [DEC], excessive collisions. TDR=[DEC]\n%PQUICC-5-COLL: Unit [DEC], excessive collisions. Retry limit [DEC] exceeded\n%PQUICC_ETHER-5-COLL: Unit [DEC], excessive collisions. Retry limit [DEC] exceeded", "choices": ["送信試行が 16 回失敗するとフレームがドロップされる", "内部送信バッファが過負荷になっている", "64 バイト未満のフレームを大量に受信する", "1518 バイトを超える過剰な数のフレームが受信される"], "answer": "送信試行が 16 回失敗するとフレームがドロップされる", "explanation": "再送信アルゴリズムは、パケットが同時に再送信されないようにするのに役立ちます。ただし、2 つのデバイスがほぼ同時に再試行すると、パケットが再び衝突する可能性があります。このプロセスは、パケットが最終的に衝突なしでネットワークに通過するか、または 16 回連続して衝突が発生してパケットが破棄されるまで繰り返されます。"},
    {"qid": "B3-M3-047", "book": "B3", "text": "以下の出力を得たとき、スイッチでは何が発生していますか。", "exhibit": "%AMD_P2_FE-5-COLL: AMDP2/FE 0/0/[DEC], Excessive collisions, TDR=[DEC], TRC=[DEC]\n%DEC21140-5-COLL: [chars] excessive collisions\n%V1LACC-5-COLL: Unit [DEC], excessive collisions. TDR=[DEC]\n%LANCE-5-COLL: Unit [DEC], excessive collisions. TDR [DEC]\n%PQUICC-5-COLL: Unit [DEC], excessive collisions. Retry limit [DEC] exceeded\n%PQUICC_ETHER-5-COLL: Unit [DEC], excessive collisions. Retry limit [DEC] exceeded", "choices": ["送信試行が 16 回失敗するとフレームがドロップされる", "内部送信バッファが過負荷になっている", "64 バイト未満のフレームを大量に受信する", "1518 バイトを超える過剰な数のフレームが受信される"], "answer": "送信試行が 16 回失敗するとフレームがドロップされる", "explanation": "エラーメッセージの\"Excessive collisions\"や\"excessive collisions\"は、ネットワーク上で発生している衝突の数が異常に多いことを示しています。衝突は、同じネットワーク上で同時にフレームを送信するデバイスが存在する場合に発生します。スイッチでは、一定回数の衝突が発生すると、そのポート上のフレームをドロップすることでネットワークの効率を保つための制御が行われます。 このエラーメッセージは、送信試行が16回失敗するとフレームがドロップされることを示しています。これは衝突の頻度が異常に高く、ネットワークの問題が存在していることを示しています。問題の解決策としては、ネットワーク上のトラフィックの過剰な衝突を引き起こす要因を特定し、ネットワークの設定やトポロジを調整することが必要です。"}
  ];
  if (typeof module !== "undefined" && module.exports) module.exports = BANKS.log;
})(typeof window !== "undefined" ? window : globalThis);
