/* 「ポートの守り（ポートセキュリティ）」（portsec）の過去問。手で直さない。
   scripts/config_access.py が out/full/master.jsonl から作る。 */
(function (global) {
  "use strict";
  var BANKS = global.BANKS = global.BANKS || {};
  BANKS.portsec = [
  {"qid": "B1-P12-059", "from": ["B1-P12-059"], "book": "B1", "text": "PC1 から SW1 および SW2 ネットワークへの接続を制限する必要があります。許可される MAC アドレスは 2 つに制限する必要があります。どの構成で会議室の接続が保護されますか。", "exhibit": "【ネットワーク図】\n\nSW1 Gi0/0/1 ── SW2 Gi0/0/1   （802.1q ／ VLANs 1, 100, 101, 102, 103）\nSW1 Gi1/0/15 ── PC1\n\nPC1 は Lobby Conference Room のアクセスポートにつながっている\nPC1： VLAN 100 ／ MAC: 0000.abcd.0004", "choices": ["interface gi1/0/15\nswitchport port-security\nswitchport port-security mac-address 0000.abcd.0004 vlan 100", "interface gi1/0/15\nswitchport port-security mac-address 0000.abcd.0004 vlan 100", "interface gi1/0/15\nswitchport port-security mac-address 0000.abcd.0004 vlan 100\ninterface switchport secure-mac limit 2", "interface gi1/0/15\nswitchport port-security\nswitchport port-security maximum 2"], "answer": "interface gi1/0/15\nswitchport port-security\nswitchport port-security maximum 2", "explanation": "シンプルにD。そもそも、PC1のMACアドレスやVLANを許可するというような条件は無い。"},
  {"qid": "B1-P14-095", "from": ["B1-P14-095", "B2-0108-02"], "book": "B1", "text": "ARPスプーフィング攻撃未遂の余波を受け、ネットワークセキュリティを評価している。ポートチャネル1がディストリビューションスイッチに向かうアクセススイッチのアップリンクインタフェースである場合、適切な保護を提供するためにアクセスレイヤスイッチに設定するのはどれか。(2つ選択)", "exhibit": "", "choices": ["ip dhcp snooping\n!\ninterface Port-channel1\nswitchport port-security maximum 1\nswitchport port-security", "ip dhcp snooping vlan 1-4094\nip dhcp snooping\n!\ninterface Port-channel1\nip dhcp snooping trust", "ip dhcp snooping vlan 1-4094\n!\ninterface Port-channel1\nswitchport protected\nswitchport port-security maximum 1", "ip arp inspection trust\n!\ninterface Port-channel1\nswitchport port-security maximum 4094\nswitchport port-security\nip verify source mac-check", "ip arp inspection vlan 1-4094\n!\ninterface Port-channel1\nip arp inspection trust"], "answer": ["ip dhcp snooping vlan 1-4094\nip dhcp snooping\n!\ninterface Port-channel1\nip dhcp snooping trust", "ip arp inspection vlan 1-4094\n!\ninterface Port-channel1\nip arp inspection trust"], "explanation": "ARPスプーフィング攻撃への対策として、アクセススイッチ（L2）側でどのようなセキュリティ設定をすべきかを問うものです。B.\"dhcp snooping\" により、信頼できないポートのDHCP応答を遮断します。\"arp inspection\"により、ARPパケットの正当性を確認します。【実践】ip dhcp snooping vlan 1-4094とip arp inspection vlan 1-4094を探しましょう。 同じ問題は B2-0108-02 にも出ます。"},
  {"qid": "B2-0016-01", "from": ["B2-0016-01"], "book": "B2", "text": "展示品をご参照ください。ネットワーク エンジニアは、新しいスイッチでポート セキュリティの構成を開始しました。次の要件を満たす必要があります。\n\n・MAC アドレスは動的に学習される必要があります。\n・不要なトラフィックが発生した場合、インターフェイスを無効にせずにログ メッセージを生成する必要があります。\n\nこのタスクを完了するには、どの 2 つのコマンドを構成する必要がありますか? (2 つお選びください。)", "exhibit": "【ネットワーク図】\n\n2台のスイッチを Gig0/1 でつないでいる\n\n【入っている設定】\nSW# conf t\nSW(config)#interface gigabitEthernet0/1\nSW(config-if)#switchport mode access\nSW(config-if)#switchport port-security\nSW(config-if)#", "choices": ["SW(config-if)#switchport port-security violation restrict", "SW(config-if)#switchport port-security mac-address 0010.7B84.45E6", "SW(config-if)#switchport port-security maximum 2", "SW(config-if)#switchport port-security violation shutdown", "SW(config-if)#switchport port-security mac-address sticky"], "answer": ["SW(config-if)#switchport port-security violation restrict", "SW(config-if)#switchport port-security mac-address sticky"], "explanation": ""},
  {"qid": "B3-M3-082", "from": ["B3-M3-082"], "book": "B3", "text": "上記を参照してください。ネットワーク環境が正常に動作している場合、インターフェイス fastethernet 0/1 にはどのタイプのデバイスを接続する必要がありますか。", "exhibit": "ip arp inspection vlan 2-10\ninterface fastethernet 0/1\n    ip arp inspection trust", "choices": ["DHCP クライアント", "アクセスポイント", "ルーター", "PC"], "answer": "ルーター", "explanation": "正解はルーターです。ルーターは、管理制御下にあるネットワーク デバイスです。したがって、DAI および DHCP スヌーピングで信頼できるように設定されます。"}
  ];
  if (typeof module !== "undefined" && module.exports) module.exports = BANKS.portsec;
})(typeof window !== "undefined" ? window : globalThis);
